config/routes.rb
Morabeteen::Application.routes.draw do
  devise_for :users, path: ''
  devise_for :admins, path: 'admin', path_names: { sign_in: 'sign-in', sign_out: 'sign-out' }

  resources :activities
  resources :leaders, only: :index
  resources :levels do
    resources :follow_up_messages
  end
  resources :users, only: :show do 
    put :update_achievement
    put :update_level
  end
  resources :schedules do
    collection do
      put :create_multiple
      put :update_multiple
    end

    member do
      get :edit_multiple
    end
  end
  
  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: "sessions#failure"
  match '/logout', to: 'sessions#destroy', as: 'logout'

  match "admin-dashboard", to: 'admin_dashboard#index', as: 'admin_dashboard'
  
  root to: 'home#index'

  match '/:controller/:action'
end

app/controllers/admin_dashboard_controller.rb
class AdminDashboardController < ApplicationController
  before_filter :authenticate_user!
  
  def index
    @activites_count = Activity.count
    authorize! :read, Activity
  end
end

app/views/admin_dashboard/index.html.haml
.container.db-wrapper
  .row
    .span3.well
      .title
        = link_to "Activites", activities_path
      .title
        = link_to "Schedule", schedules_path

  .main
    %ul#rb-grid.rb-grid.clearfix
      %li.icon-clima-1.rb-span-2
        %h3
          London
        %span.rb-temp 21°C
        .rb-overlay
          %span.rb-close close
          .rb-week
            %div
              %span.rb-city Lisbon
              %span.icon-clima-1
              %span 21°C
            %div
              %span Mon
              %span.icon-clima-1
              %span 19°C
            %div
              %span Tue
              %span.icon-clima-2
              %span 19°C
            %div
              %span Wed
              %span.icon-clima-2
              %span 18°C
            %div
              %span Thu
              %span.icon-clima-2
              %span 17°C
            %div
              %span Fri
              %span.icon-clima-1
              %span 19°C
            %div
              %span Sat
              %span.icon-clima-1
              %span 22°C
            %div
              %span Sun
              %span.icon-clima-1
              %span 18°C
      %li.icon-clima-2
        %h3
          Paris
        %span.rb-temp 11°C
        .rb-overlay
          %span.rb-close close
          .rb-week
            %div
              %span.rb-city
              %span.icon-clima-2
              %span 11°C
            %div
              %span Mon
              %span.icon-clima-1
              %span 12°C
            %div
              %span Tue
              %span.icon-clima-4
              %span 11°C
            %div
              %span Wed
              %span.icon-clima-4
              %span 10°C
            %div
              %span Thu
              %span.icon-clima-4
              %span 9°C
            %div
              %span Fri
              %span.icon-clima-2
              %span 10°C
            %div
              %span Sat
              %span.icon-clima-2
              %span 10°C
            %div
              %span Sun
              %span.icon-clima-2
              %span 12°C
      %li.icon-clima-1
        %h3 Belgrade
        %span.rb-temp 15°C
        .rb-overlay
          %span.rb-close close
          .rb-week
            %div
              %span.rb-city Belgrade
              %span.icon-clima-1
              %span 15°C
            %div
              %span Mon
              %span.icon-clima-3
              %span 16°C
            %div
              %span Tue
              %span.icon-clima-3
              %span 17°C
            %div
              %span Wed
              %span.icon-clima-3
              %span 15°C
            %div
              %span Thu
              %span.icon-clima-4
              %span 13°C
            %div
              %span Fri
              %span.icon-clima-3
              %span 10°C
            %div
              %span Sat
              %span.icon-clima-1
              %span 11°C
            %div
              %span Sun
              %span.icon-clima-1
              %span 12°C
      

= javascript_include_tag "boxgrid"
= javascript_include_tag "jquery.fittext"
:javascript
  $(function(){Boxgrid.init()});