config/routes.rb
Morabeteen::Application.routes.draw do
  devise_for :users, path: ''
  devise_for :admins, path: 'admin', path_names: { sign_in: 'sign-in', sign_out: 'sign-out' }

  resources :activities
  resources :leaders, only: :index
  resources :levels do
    resources :follow_up_messages
  end
  resources :users, only: :show do 
    put :update_achievement
    put :update_level
  end
  resources :schedules do
    collection do
      put :create_multiple
      put :update_multiple
    end

    member do
      get :edit_multiple
    end
  end
  
  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: "sessions#failure"
  match '/logout', to: 'sessions#destroy', as: 'logout'

  match "admin-dashboard", to: 'admin_dashboard#index', as: 'admin_dashboard'
  
  root to: 'home#index'

  match '/:controller/:action'
end

app/controllers/follow_up_messages_controller.rb
class FollowUpMessagesController < ApplicationController
  load_and_authorize_resource :level
  load_and_authorize_resource :follow_up_activity_message, through: :level

  def index
    @messages = @level.follow_up_activity_messages
    @message = params[:message] ? FollowUpActivityMessage.find(params[:message]) : FollowUpActivityMessage.new
  end

  def create
    @message = @level.follow_up_activity_messages.new params[:follow_up_activity_message]
    if @message.save
      redirect_to level_follow_up_messages_path(@level), notice: t('follow_up.created_successfuly')
    else
      redirect_to level_follow_up_messages_path([@level], message: @message), flash: {error: t('follow_up.fail_to_create')}
    end
  end

  def update
    @message = @level.follow_up_activity_messages.find params[:id]
    if @message.update_attributes(params[:follow_up_activity_message])
      redirect_to level_follow_up_messages_path(@level), notice: t('follow_up.updated_successfuly')
    else
      redirect_to level_follow_up_messages_path([@level], message: @message), flash: {error: t('follow_up.fail_to_update')}
    end
  end

  def destroy
    @message = @level.follow_up_activity_messages.find params[:id]
    if @message.destroy
      redirect_to level_follow_up_messages_path(@level), notice: t('follow_up.deleted_successfuly')
    else
      redirect_to level_follow_up_messages_path([@level], message: @message), flash: {error: t('follow_up.fail_to_delete')}
    end
  end

end

app/views/follow_up_messages/_follow_up_activity_message_fields.html.haml
.span8.well.message-fields
  - unless new_record
    = link_to t('follow_up.new_record'), level_follow_up_messages_path(@level.id), class: "btn"
  = f.error_messages header_tag: 'h4', message: nil, class: 'alert alert-error'
  %h5
    = t('follow_up.score_range')
  = f.number_field :start_range, class: "span3", placeholder: t('follow_up.from_example')
  = f.number_field :end_range, class: "span3", placeholder: t('follow_up.to_example')
  .control-group
    = f.label :activity
    = f.select :activity_id, involved_activities(@level)
  .control-group
    = f.label :message, class: "control-label"
    .controls
      = f.text_area :message, placeholder: t('follow_up.message'), class: "tinymce span7", rows: 10
      = tinymce
  .row-fluid
    = f.submit "Save", class: "btn btn-success"

app/views/follow_up_messages/index.html.haml
%ul.breadcrumb
  %li
    = link_to t('common.schedules'), schedules_path
    %span.divider
  %li
    = link_to t('common.follow_up_messages'), level_follow_up_messages_path(@level.id), class: "active"
    %span.divider
= tinymce_assets
- new_record = @message.new_record?
= form_for @message, url: (new_record ? level_follow_up_messages_path(@level.id) : level_follow_up_message_path(@level.id, @message)), method: (new_record ? :post : :put), class: "form-inline" do |f|
  = render partial: "follow_up_activity_message_fields", locals: {f: f, new_record: new_record}
.span7.messages-table
  %table.table.table-striped
    %thead
      %tr
        %th Start range
        %th End range
        %th message
        %th
    %tbody
      - if @messages.empty?
        %tr.info
          %td{colspan: 4}
            = t('follow_up.no_messages_yet')
      - else
        - grouped_messages = @messages.group_by(&:activity)
        - grouped_messages.keys.each do |activity|
          %tr.info
            %td{colspan: 4}
              - if activity
                = activity.try(:title)
              - else
                = t('activity.general')
          - grouped_messages[activity].each do |message|
            %tr
              %td= message.start_range
              %td= message.end_range
              %td= raw(message.message).truncate(30)
              %td
                = link_to t("common.view"), level_follow_up_messages_path([@level], message: message)
                |
                = link_to t("common.delete"), level_follow_up_message_path(@level, message), method: :delete