config/routes.rb
Morabeteen::Application.routes.draw do
  devise_for :users, path: ''
  devise_for :admins, path: 'admin', path_names: { sign_in: 'sign-in', sign_out: 'sign-out' }

  resources :activities
  resources :leaders, only: :index
  resources :levels do
    resources :follow_up_messages
  end
  resources :users, only: :show do 
    put :update_achievement
    put :update_level
  end
  resources :schedules do
    collection do
      put :create_multiple
      put :update_multiple
    end

    member do
      get :edit_multiple
    end
  end
  
  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: "sessions#failure"
  match '/logout', to: 'sessions#destroy', as: 'logout'

  match "admin-dashboard", to: 'admin_dashboard#index', as: 'admin_dashboard'
  
  root to: 'home#index'

  match '/:controller/:action'
end

app/models/achievement.rb
class Achievement
  include Mongoid::Document
  include Mongoid::Timestamps

  # Fields
  field :date, type: Date

  # Associations
  belongs_to :user
  has_and_belongs_to_many :completed_tasks, class_name: 'Task', inverse_of: nil, after_add: :assing_level, after_remove: :unassign_level
  belongs_to :schedule

  # Attr 
  attr_accessor :unchecked_task

  # Scopes
  scope :for, ->(date) { where(date: date)}
  scope :for_users, ->(users){where(:user.in => users)}
  scope :for_range, ->(start_range, end_range) { between(date: start_range..end_range)}
  scope :with_level, ->{where(:level.ne => nil)}

  after_create ->{self.assing_level(completed_tasks.first)}

  validates_presence_of :date, :user

  def total_score
    self.completed_tasks.sum(:points)
  end

  def self.calculate_activity_score(achievements, activity)
    result = 0
    achievements.each do |a|
      result += a.completed_tasks.for_activity(activity).sum(:points)
    end
    result
  end

  def self.total_score(achievements)
    score = 0
    achievements.each{ |a| score += a.completed_tasks.sum(:points) }
    score
  end

  protected

  def assing_level(e)
    unless self.user.level(self.date)
      schedule = e.activity_task.schedule
      user_level = self.user.levels.create(start_date: schedule.start_date, end_date: schedule.end_date, level: schedule.level)
    end
    user_level
  end

  def unassign_level(e)
    completed_tasks = self.completed_tasks - [e]
    self.user.level(self.date).destroy && self.destroy if completed_tasks.empty? && self.user.level(self.date)
  end

end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Slug

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
        :rememberable, :trackable

  # Constants
  GENDERS = [:male, :female]

  GENDER_PREFIX_CODE = {
    male: "11",
    female: "10"
  }
  ROLES = [:admin, :default]

  ## Database authenticatable
  field :encrypted_password, :type => String, :default => ""
  field :username,            type: String
  # field :email
  
  ## Recoverable
  field :reset_password_token,   :type => String
  field :reset_password_sent_at, :type => Time

  ## Rememberable
  field :remember_created_at, :type => Time

  ## Trackable
  field :sign_in_count,      :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String

  ## Confirmable
  # field :confirmation_token,   :type => String
  # field :confirmed_at,         :type => Time
  # field :confirmation_sent_at, :type => Time
  # field :unconfirmed_email,    :type => String # Only if using reconfirmable

  # Fields
  # field :first_name
  # field :last_name
  # field :facebook_uid
  field :gender,             type: Symbol
  # field :code_name,          type: String
  field :role,               type: Symbol

  attr_accessor :choosen_level

  #Extensions
  slug :username
  # mount_uploader :avatar, AvatarUploader
  
  # Relations
  has_many :achievements
  has_many :levels, class_name: "UserLevel", inverse_of: :user
  
  # Validations
  validates_presence_of :gender
  validates_presence_of   :password, :on=>:create
  validates_confirmation_of   :password, :on=>:create
  validates_length_of :password, :within => Devise.password_length, :allow_blank => true
  # check on format no whitespaces
  validates :username, :uniqueness => { :case_sensitive => false}

  # Callbacks
  # before_create :generate_code
  # before_create :skip_confirmation_mail, if: ->{self.facebook_uid.present?}
  # before_create :skip_confirmation_mail


  scope :females, where(gender: :female)
  scope :males, where(gender: :male)
  # Methods
  def name
    "#{first_name} #{last_name}"
  end

  # def email_required?
  #   false
  # end

  # def self.find_first_by_auth_conditions(warden_conditions)
  #   conditions = warden_conditions.dup
  #   if username = conditions.delete(:username)
  #     self.where(username: /^#{Regexp.escape(login)}$/i).first
  #   else
  #     super
  #   end
  # end
  # def self.from_omniauth(auth)
  #   find_by(facebook_uid: auth["uid"]) || create_with_omniauth(auth)
  # end

  # def self.create_with_omniauth(auth)
  #   user = find_by(email: auth["info"]["email"])
  #   params = {facebook_uid: auth["uid"], first_name: auth["info"]["first_name"], last_name: auth["info"]["last_name"]}
  #   return user.update_attributes(params) if user.present?
  #   return User.create(params.merge!({email: auth["info"]["email"], password: Devise.friendly_token[0,20], gender: auth["extra"]["raw_info"]["gender"]}))
  # end


  ################# REDO THE FOLLOWING METHODS ACCORDING TO THE NEW STRUCTURE
  def self.calculate_general_achievements_stats(zone, start_range, end_range)
    achievements = Achievement.for_users(self.send(zone.to_s.pluralize.to_sym).to_a).for_range(start_range, end_range)
    user_scores = Hash.new
    achievements.each{ |a| user_scores[a.user] = (user_scores[a.user] || 0) + a.completed_tasks.sum(:points) }
    Hash[*user_scores.sort_by{|k,v| v}.reverse.flatten.take(10)]
  end

  def self.calculate_activities_achievements_stats(zone, start_range, end_range)
    achievements = Achievement.for_users(self.send(zone.to_s.pluralize.to_sym).to_a).for_range(start_range, end_range)
    involved_activities = Schedule.zone(zone).with_start_and_end(start_range, end_range).map{|s| s.tasks.map(&:activity)}.flatten.uniq
    User.get_top_in_activities(achievements, involved_activities)
  end

  def self.get_top_in_activities(achievements, activities)
    results = Hash.new
    achievements = achievements.group_by(&:user)
    activities.each do |act|
      results[act.title] = Hash.new
      achievements.keys.each{|a| results[act.title][a] = (results[act.title][a] || 0) + Achievement.calculate_activity_score(achievements[a], act)}
      results[act.title] = Hash[*results[act.title].sort_by{|k,v| v}.reverse.take(10).flatten]
    end
    results
  end
  ############## end of redo ###################

  # Follow up for each user 
  def self.follow_up_report(zone, start_range, end_range)
    achievements = Achievement.for_users(self.send(zone.to_s.pluralize.to_sym).to_a).for_range(start_range, end_range)
    # zone_schedules = Schedule.zone(:male).with_start_and_end(start_range, end_range)
    zone_schedules = Schedule.zone(zone)
    activities_w_scores = Hash.new
    zone_schedules.each do |s|
      activities_w_scores[s] = s.activitis_score_hash
    end
    follow_up_messages = FollowUpActivityMessage.for_levels(zone_schedules.map(&:level).flatten.uniq)
    User.think(achievements, activities_w_scores, follow_up_messages, start_range, end_range)
  end


  def self.think(achievements, activities_hash, messages, start_range, end_range)
    results = Hash.new
    users_ach = achievements.group_by(&:user)
    users_ach.keys.each do |user|
      results[user] = user.prepare_user_score_hash(users_ach[user], activities_hash)
      # date_ach: hash of keys[date] and values = achievements
      date_ach = users_ach[user].group_by(&:date)
      # get selected schedule for the week or the first few days
      selected_schedule = user.first_selected_schedule_from_achievements(start_range, date_ach, end_range)
      # Looping through week days and calculates each day score and updates the results[user] hash with the calculated values
      user.calculate_days_score_hash(start_range, end_range, date_ach, selected_schedule, results[user], activities_hash)
      user.follow_up_messages_with_score(messages, results[user], user.level(start_range).level)
    end
    results
  end

  def calculate_days_score_hash(start_range, end_range, date_ach, selected_schedule, user_hash, activities_hash)
    start_range.upto(end_range).each do |date|
      ## act_tasks_ach: hash of keys[activity_task] and values = completed_task
      if date_ach[date]
        schedule_date_ach = date_ach[date].group_by(&:schedule)
        schedule_date_ach.keys.each{|s| schedule_date_ach[s] = schedule_date_ach[s].map(&:completed_tasks).flatten.group_by{|t| t.activity_task.activity}}
      end
      user_hash.keys.each do |s|
        next if selected_schedule && selected_schedule != s
        user_hash[s].keys.each do |ac|
          total_score = activities_hash[s][ac]
          day_score = date_ach[date] && schedule_date_ach[s][ac] ? schedule_date_ach[s][ac].map(&:points).flatten.inject(0, :+) : 0
          user_hash[s][ac] << ((day_score/(total_score*1.0))*100).ceil
        end
      end
      selected_schedule = self.day_selected_schedule(selected_schedule, date_ach[date+1])
    end
  end

  def day_selected_schedule(prev_selected_schedule, day_achievements)
    case day_achievements.try(:count)
    when 1
      day_achievements.first.schedule
    when 2
      nil
    else
      prev_selected_schedule
    end
  end

  def follow_up_messages_with_score(messages, user_hash, user_level)
    user_hash.keys.each do |s|
      user_hash[s].keys.each do |a|
        unless user_hash[s][a].empty?
          tmp_hash = Hash.new
          tmp_hash[:score] = (user_hash[s][a].flatten.inject(0, :+) / (user_hash[s][a].count*1.0)).ceil
          tmp_hash[:message] = messages.level(user_level).activity(a).range(tmp_hash[:score]).try(:first).try(:message)
          user_hash[s][a] = tmp_hash
        end
      end
    end
  end

  def first_selected_schedule_from_achievements(start_range, date_ach, end_range)
    first_date = start_range
    while date_ach[first_date].nil? && first_date <= end_range
      first_date += 1
    end
    date_ach[first_date].first.schedule if date_ach[first_date].count == 1
  end

  def prepare_user_score_hash(users_ach, activities_hash)
    results = Hash.new
    users_ach.map(&:schedule).flatten.each do |s|
      results[s] = Hash.new 
      activities_hash[s].keys.each { |a| results[s][a] = []}
    end
    results
  end

  def calculate_activity_score(achievements, user_hash, activities)
    activities.each { |a| user_hash[a] = 0 }
    # get achievements by day and get percentage for this day according to completed tasks schedule
    temp_hash = Hash.new
    achievements.group_by(&:date).values.each do |a|
      schedules = a.completed_tasks.flatten.group_by(&:schedule)
      grouped_tasks = schedules.group_by(&:activity)
      grouped_tasks.keys.each do |ac|
        grouped_tasks[ac].map(&:points).flatten.inject(0, :+)
        temp_hash[ac] += []
      end
    end
    achievements.map(&:completed_tasks).flatten.each do |t|
      user_hash[t.activity] += t.points
    end
  end

  def role?(role)
    self.role == role
  end

  def schedules(date)
    Schedule.zone(self.gender.downcase).within(date)
  end

  def completed?(task, date)
    self.achievements.where(date: date).first.try(:completed_tasks).try(:include?, task)
  end

  def completed_task_ids
    self.achievements.map(&:completed_task_ids).flatten
  end

  def completed_tasks_by_day(achievements=nil)
    results = Hash.new
    achievements = achievements || self.achievements
    achievements.each { |a| results[a.date] = (results[a.date] || [] )+ a.completed_tasks}
    results
  end

  def total_points(achievements, start_range=nil, end_range=nil)
    score = unless start_range
              achievements
            else
              achievements.for_range(start_range, end_range)

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource

  respond_to :html, :js

  def show
    @schedules = current_user.schedules(Date.today).asc(:start_date)
    @completed_tasks = current_user.completed_tasks_by_day
    @achievements = current_user.achievements
  end

  def update_achievement
    removed_task = Task.find(params[:achievement][:unchecked_task]) if params[:achievement][:unchecked_task]
    checked_task = Task.find(params[:achievement][:completed_task_ids]) if params[:achievement][:completed_task_ids]
    if @achievement = current_user.achievements.find_by(date: params[:achievement][:date].to_date, schedule_id: params[:achievement][:schedule_id])
      unless removed_task
        completed_tasks = [checked_task].flatten - @achievement.completed_tasks
        @achievement.completed_tasks.push(completed_tasks) unless completed_tasks.empty?
      else
        @achievement.completed_tasks.delete(removed_task)
      end
    else
      @achievement = current_user.achievements.create params[:achievement]
    end
    @schedules = current_user.level(Date.today).try(:level).try(:schedules) || Schedule.zone(current_user.gender).for_range(params[:achievement][:date])
    @achievements = current_user.achievements
    @completed_tasks = current_user.completed_tasks_by_day(@achievements)
    @date = params[:achievement][:date]
    @selected_schedule = @achievement.schedule
    @total_acc_score = current_user.total_points(@achievements)
    @current_level = current_user.level(params[:achievement][:date]).try(:level)
    @current_week_score = current_user.total_points(@achievements, @schedules.first.start_date, @schedules.first.end_date)

    @response = {schedules: @schedules, date: @date, selected_schedule: @selected_schedule, completed_task_ids: @completed_tasks, acc_score: @total_acc_score, week_score: @current_week_score,
                  current_level: @current_level}
    respond_with @response, location: user_path(current_user)
  end

  def update_level
    @level = Level.find params[:user][:choosen_level]
    @schedules = @level.schedules
    @start_range = Date.today
    @end_range = @schedules.first.start_date
    @response = {level: @level, schedules: @schedules, start_range: @start_range, end_range: @end_range}
    respond_with @response
  end
end

app/helpers/users_helper.rb
module UsersHelper
  
  def get_schedule(date, schedules)
    schedules.collect { |c| c if c.start_date <= date && c.end_date >= date}.compact
  end

  def schedules_select(schedules, f, date, completed_tasks)
    options = []
    schedules.each do |schedule|
      partial = render(partial: 'users/schedule', locals: {f: f, schedule: schedule, date: date, completed_tasks: completed_tasks})
      options << [schedule.title, schedule.id, {:'data-partial' => partial.gsub("\n", "")}]
    end
    options
  end

  def check_completed(task, date, completed_tasks)
    completed_tasks.try(:include?, task) || false
  end

  def day_score(date)
    current_user.achievements.for(date).map{ |a| a.total_score }.flatten.inject(0, :+)
  end

  def get_selected(schedules, selected)
    return schedules.select{|s| s==selected}.first if selected.present?
    return schedules.first
  end

  def total_acc_score
    current_user.total_points(@achievements)
  end

  def total_week_score(start_date, end_date)
    current_user.total_points(@achievements, start_date, end_date)
  end

  def level_select(levels)
    options = []
    levels.each do |level|
      options << [level.name, level.id]
    end
    options
  end

  def ended_schedules?(schedules)
    schedules.first.ended?
  end

  def current_level(date)
    current_user.level(date)
  end

  def missed_schedule?(start_date, end_date)
    current_user.achievements.for_range(start_date, end_date).empty? && end_date < Date.today
  end

  def show_level_select?(start_date, end_date, schedules)
    ended_schedules?(schedules) || current_user.level(start_date).present?
  end

  def level_schedules(schedules, user_level)
    if user_level
      schedules.keep_if{|s| s.level == user_level}
    else
      schedules
    end
  end

  def get_selected_schedule_for_date(date)
    @achievements.for(date).desc(:updated_at).try(:first).try(:schedule)
  end
end

app/views/users/_day_score.html.haml
اجمالى نقاط اليوم
= day_score(date)

app/views/users/_level_select.html.haml
%span.level-select.clearfix
  - unless show_level_select?(start_date, end_date, schedules)
    = form_for current_user, url: user_update_level_path(current_user.id), method: :put, remote: true do |f|
      = f.select :choosen_level, level_select(schedules.map(&:level).uniq), {}, {class: "span3", id: "level-select"}
  - else
    = t('level.selected_level_for_week')
    = current_level.name

app/views/users/_populate_timeline.html.haml
- (start_range.downto(end_range)).each do |date|
  %li
    .form{id: "#{date.strftime('%y%m%d')}-form"}
      .schedule-item
        = render partial: 'users/schedule-form', locals: {date: date, schedules: schedules, selected_schedule: nil, completed_tasks: completed_tasks}

app/views/users/_schedule-form.html.haml
- option_selected_schedule = selected_schedule || get_selected_schedule_for_date(date)
- if completed_tasks.empty?
  - completed_tasks = []
- else
  - completed_tasks = completed_tasks[date]
= form_for @achievement || Achievement.new, url: user_update_achievement_path(current_user.id), method: :put, remote: true, format: :js, class: "achievement-form form-inline" do |f|
  .header.clearfix
    .pull-right
      .day-score{id: "#{date.strftime('%y%m%d')}-day-score"}
        = render partial: 'users/day_score', locals: {date: date}

    .calendar.pull-left
      .date
        = date.strftime('%a, %d %b')
      
    = f.hidden_field :date, value: date
    
    = f.hidden_field :unchecked_task, class: "achievement-unchecked-task"
    
    - first_schedule = get_selected(schedules, option_selected_schedule)
    
    - if schedules.count > 1
      = f.select :schedule_id, schedules_select(schedules, f, date, completed_tasks), {selected: option_selected_schedule.try(:id)}, {id: "#{date.strftime('%y%m%d')}_achievement_schedule", class: "span2"}
    - else
      = f.hidden_field :schedule_id, value: first_schedule.id

  .content.clearfix
    .schedule-form{id: "#{date.strftime('%y%m%d')}"}
      = render partial: 'users/schedule', locals: {schedule: first_schedule, f: f, date: date, completed_tasks: completed_tasks}

app/views/users/_schedule.html.haml
- schedule.activity_tasks.each do |act|
  .activiy
    .activity-header
      = act.activity.title
    .span12
      - act.tasks.each do |task|
        .span3
          %label
            = check_box_tag 'achievement[completed_task_ids][]', task.id, check_completed(task, date, completed_tasks), class: "checkable-task"
            %span
              = task.description

app/views/users/show.html.haml
.container.user-schedule
  .row
    .span1
      .schedule-track
        .track-inner

    .span11
      .time-line
        .block.sorting
          .track-icon
            %i.icon-cog
          %h5
            اختر المرحله لهذا الاسبوع
          %p
            أم عليها المشتّتون تعد. كل وضم الصيني وقدّموا. قد يتبقّ الإمداد ولم, الضغوط الإتحاد أي يكن. لم النمسا الإيطالية انه, أي زهاء الألماني عدم, عقبت تشكيل النمسا بين ما. مقاطعة والنرويج كل كلّ. في الخارجية المدنيين كلّ, الجبهة باستحداث من حتى.

            لكل ان معارضة للإتحاد هيروشيما. يرتبط تكتيكاً في ومن, استرجاع تكبّلتها عل حدى, ثم إيو مرمى أدولف اليميني. ثم وقد العالم، اليميني, شبح إذ هامش بولندا،. هو إختار وسمّيت به،, العدّ وتنامت ٣٠ دنو, أن أضف مسارح واستمر الدولارات. إذ لفشل بالسيطرة مكن.
        - 5.times do
          .block
            .track-icon
              %i.icon-calendar
            .current-date
              الجمعه , ١٧ يناير
            .data
              .row
                .span3.activity-block
                  %h4.activity-name
                    الصلاه
                  .activity-content
                    أم عليها المشتّتون تعد. كل وضم الصيني وقدّموا. قد يتبقّ الإمداد ولم, الضغوط الإتحاد أي يكن. لم النمسا الإيطالية انه, أي زهاء الألماني عدم, عقبت تشكيل النمسا بين ما. مقاطعة والنرويج كل كلّ. في الخارجية المدنيين كلّ, الجبهة باستحداث من حتى.

                .span3.activity-block
                  %h4.activity-name
                    الصوم
                  .activity-content
                    أم عليها المشتّتون تعد. كل وضم الصيني وقدّموا. قد يتبقّ الإمداد ولم, الضغوط الإتحاد أي يكن. لم النمسا الإيطالية انه, أي زهاء الألماني عدم, عقبت تشكيل النمسا بين ما. مقاطعة والنرويج كل كلّ. في الخارجية المدنيين كلّ, الجبهة باستحداث من حتى.

                .span3.activity-block
                  %h4.activity-name
                    القيام
                  .activity-content
                    أم عليها المشتّتون تعد. كل وضم الصيني وقدّموا. قد يتبقّ الإمداد ولم, الضغوط الإتحاد أي يكن. لم النمسا الإيطالية انه, أي زهاء الألماني عدم, عقبت تشكيل النمسا بين ما. مقاطعة والنرويج كل كلّ. في الخارجية المدنيين كلّ, الجبهة باستحداث من حتى.


/ .profile-wrapper
/   .container
/     .profile-header.row
/       .user-avatar.pull-left
/         = image_tag 'avatar.png', class: 'img-polaroid'
/         / = image_tag @user.avatar.profile.url
/       .user-info
/         .span3
/           .user-name
/             / = @user.name
/             عمر بن الخطاب
/         %ul.badges-list
/           %li.badges.abubakr
/           %li.badges.abuobayda
/           %li.badges.omr
/           %li.badges.ali
/         .pull-right
/           .span2.action-info
/             %label
/               اجمالى النقاط
/               / %span{id: "#{@user.id}-acc-score"}
/               = total_acc_score

/     %br

/     .timeline-wrapper.row
/       - if @schedules.present?
/         - grouped_schedules = @schedules.desc(:start_date).group_by(&:start_date)
/         - grouped_schedules.keys.each_with_index do |s,x|
/           - start_date = grouped_schedules[s].first.start_date
/           - end_date = grouped_schedules[s].first.end_date
/           - user_level = current_user.level(start_date)
/           - current_level = user_level.level if user_level
/           - level_schedules = level_schedules(grouped_schedules[s], current_level)
/           - unless missed_schedule?(start_date, end_date)
/             .week-wrapper.clearfix
/               .span3
/                 %h5
/                   اختر المرحله لهذا الاسبوع

/               .span4.week-level
/                 %span.day-activity
/                   .schedule-item{id: "option-level-select"}
/                     = render partial: "level_select", locals: {start_date: start_date, end_date: end_date, schedules: grouped_schedules[s], current_level: current_level}

/                   - start_range = x == 0 ? (grouped_schedules[s].first.end_date < Date.today  ? grouped_schedules[s].first.end_date : Date.today) : grouped_schedules.keys[x-1] - 1

/               .span2.offset2.week-points
/                 %label
/                   اجمالى نقاط الاسبوع
/                   %span{id: "#{start_range.strftime('%y%m%d')}-week-score"}
/                     = total_week_score(s, start_range)

/             %ul.days-activity.row
/               .schedule{id: "#{start_range}-to-#{s}"}
/                 = render partial: 'users/populate_timeline', locals: {start_range: start_range, end_range: s, schedules: grouped_schedules[s], completed_tasks: @completed_tasks}
/       - else
/         %p
/           No schedules yet!

/ .timeline.flow
/   .main-content.clearfix
/     %section.schedule-activity
/       #days-activity
/         %ul.schedules
/           - if @schedules.present?
/             - grouped_schedules = @schedules.desc(:start_date).group_by(&:start_date)
/             - grouped_schedules.keys.each_with_index do |s,x|
/               - start_date = grouped_schedules[s].first.start_date
/               - end_date = grouped_schedules[s].first.end_date
/               - user_level = current_user.level(start_date)
/               - current_level = user_level.level if user_level
/               - level_schedules = level_schedules(grouped_schedules[s], current_level)
/               - unless missed_schedule?(start_date, end_date)
/                 %li.clearfix
/                   .calendar
/                     .date
/                       = t('level.selected')
/                   .schedule-item{id: "option-level-select"}
/                     = render partial: "level_select", locals: {start_date: start_date, end_date: end_date, schedules: grouped_schedules[s], current_level: current_level}

/                 - start_range = x == 0 ? (grouped_schedules[s].first.end_date < Date.today  ? grouped_schedules[s].first.end_date : Date.today) : grouped_schedules.keys[x-1] - 1
/                 %li.week-points.clearfix
/                   .calendar
/                     .date
/                       = t('achievement.week_score')
/                   .schedule-item
/                     .content.clearfix
/                       %h4
/                         %span.numbers{id: "#{start_range.strftime('%y%m%d')}-week-score"}
/                           = total_week_score(s, start_range)
/                         = t('common.points')
/                 %ul
/                   .schedule{id: "#{start_range}-to-#{s}"}
/                     = render partial: 'users/populate_timeline', locals: {start_range: start_range, end_range: s, schedules: grouped_schedules[s], completed_tasks: @completed_tasks}
/           - else
/             No schedules yet!

app/views/users/update_achievement.js.erb
<%- @schedules = @response[:schedules] %>
<%- @date = @response[:date] %>
<%- date_id = @date.to_date.strftime("%y%m%d") %>
schedule_data = "<%= escape_javascript(render partial: 'users/schedule-form', locals: {schedules: @schedules, date: @date.to_date, selected_schedule: @response[:selected_schedule], completed_tasks: @response[:completed_task_ids]}) %>";
$("#<%= date_id %>-form .schedule-item").html(schedule_data);
$("#<%= current_user.id %>-acc-score").html(<%= @response[:acc_score] %>);
$("#<%= date_id %>-week-score").html("<%= @response[:week_score] %>");
level = "<%= escape_javascript(render partial: 'users/level_select', locals: {schedules: @schedules, end_date: @schedules.first.end_date, start_date: @schedules.first.start_date, current_level: @response[:current_level]}) %>";
$("#option-level-select").html(level);
$('select').selectpicker();

app/views/users/update_level.js.erb
<%- @start_range = @response[:start_range].to_date %>
<%- @end_range = @response[:end_range].to_date %>
timeline_data = "<%= escape_javascript(render partial: 'users/populate_timeline', locals: {schedules: @response[:schedules], start_range: @start_range, end_range: @end_range, completed_tasks: []}) %>";
$("#<%= @response[:start_range].to_date %>-to-<%= @response[:end_range].to_date %>").html(timeline_data);
$('select').selectpicker();