config/routes.rb
Morabeteen::Application.routes.draw do
  devise_for :users, path: ''
  devise_for :admins, path: 'admin', path_names: { sign_in: 'sign-in', sign_out: 'sign-out' }

  resources :activities
  resources :leaders, only: :index
  resources :levels do
    resources :follow_up_messages
  end
  resources :users, only: :show do 
    put :update_achievement
    put :update_level
  end
  resources :schedules do
    collection do
      put :create_multiple
      put :update_multiple
    end

    member do
      get :edit_multiple
    end
  end
  
  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: "sessions#failure"
  match '/logout', to: 'sessions#destroy', as: 'logout'

  match "admin-dashboard", to: 'admin_dashboard#index', as: 'admin_dashboard'
  
  root to: 'home#index'

  match '/:controller/:action'
end

app/models/schedule.rb
class Schedule
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::MultiParameterAttributes
  include Mongoid::Slug

  # Constants
  ZONES = [:male, :female]

  # Fields
  field :title
  field :start_date, type: Date
  field :end_date, type: Date
  field :zone, type: Symbol

  # Associations
  belongs_to :level
  has_many :activity_tasks, inverse_of: :schedule, dependent: :destroy

  accepts_nested_attributes_for :activity_tasks, allow_destroy: true, reject_if: ->(attrs){empty_task?(attrs)}
  # Scopes
  scope :zone, ->(zone){ where(zone: zone)}
  scope :for, ->(date){ where(start_date: date)}
  scope :for_range, ->(date){where(:start_date.lte => date, :end_date.gte => date)}
  scope :within, ->(date){ where(start_date:(date.prev_month..date))}
  scope :with_start_and_end, ->(start, end_date){where(start_date: start, end_date: end_date)}
  scope :ended, ->{ where(:end_date.lt => Date.today) }

  # Callbacks
  before_destroy :check_if_can_destroy
  after_destroy :clear_level_if_last
  after_create :notify_users_delayed, :set_stats_delayed_job


  # Validations
  # TODO

  # Extensions
  slug :title

  def self.update_multiple_schedules(schedules, params)
    updated = true
    schedules.each do |schedule|
      updated &= schedule.update_attributes(params[schedule.id.to_s])
    end
    updated
  end

  def self.empty_task?(attrs)
    attrs[:tasks_attributes].empty?
  end

  def self.notify_users(schedule_id)
    schedule = Schedule.find(schedule_id)
    users = User.send(schedule.zone.to_s.pluralize.to_sym)
    UserMailer.schedule_started(users, schedule).deliver
  end

  def self.calculate_winners(schedule_id)
    schedule = Schedule.find(schedule_id)
    users_to_notify = User.calculate_general_achievements_stats(schedule.zone, schedule.start_date, schedule.end_date)
    users_to_notify.keys.each_with_index do |user, rank|
      UserMailer.notify_winner(user, rank+1, schedule).deliver
    end
  end

  def self.automated_follow_up(schedule_id)
  end

  def self.last_schedule(zone)
    Schedule.zone(zone).ended.desc(&:start_date).first
  end

  def check_if_can_destroy
    self.start_date < Date.today ? false : true
  end

  def ended?
    self.end_date < Date.today
  end

  def tasks_count
    self.activity_tasks.map(&:tasks).flatten.count
  end

  def total_points
    self.activity_tasks.map{|a| a.total_points}.flatten.inject(0, :+)
  end

  def activitis_score_hash
    resutls = Hash.new
    self.activity_tasks.each{|at| resutls[at.activity] = at.tasks.sum(:points)}
    resutls
  end

  protected

  def clear_level_if_last
    self.level.destroy unless self.level.schedules.present?
  end

  def notify_users_delayed
    run_at = self.start_date < Date.today ? Time.now : self.start_date.to_datetime
    Schedule.delay(queue: "schedules", run_at: run_at).notify_users(self.id)
  end

  def set_stats_delayed_job
    Schedule.delay(queue: "winners", run_at: (self.end_date + 1).to_datetime.change(hour: 12)).calculate_winners(self.id)
  end


end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource

  respond_to :html, :js

  def index
    @schedules = @schedules.desc(:created_at).zone(current_user.gender)
  end

  def show
  end

  def edit
  end

  def update
    if @schedule.update_attributes params[:schedule]
      flash[:notice] = "Successfully updated schedule"
    end
    respond_with @schedule
  end

  def new
    num_of_records = @zone.to_sym == :female ? 2 : 1
    @schedules = Array.new(num_of_records) {Schedule.new}
  end

  def create
    @schedule = Schedule.new params[:schedule]
    if @schedule.save
      flash[:notice] = "Successfully created schedule"
    end
    respond_with @schedule
  end

  def destroy
    if @schedule.destroy
      flash[:notice] = "Successfully deleted schedule"
    end
    respond_with @schedule, location: schedules_path
  end

  def edit_multiple
    @schedules = Schedule.zone(current_user.gender).for(@schedule.start_date)
    @start_date = @schedule.start_date
    @end_date = @schedule.end_date
  end

  def update_multiple
    start_date = *params[:start_date].values_at(:year, :month, :day).map{|c| c.to_i}
    end_date = *params[:end_date].values_at(:year, :month, :day).map{|c| c.to_i}
    @schedules = Schedule.zone(current_user.gender).with_start_and_end(params[:prev_start_date].to_date, params[:prev_end_date].to_date)
    if @schedules.update_all(start_date: start_date, end_date: end_date)
      flash[:notice] = "Successfully updated schedules date."
    end 
    respond_with @schedules, location: schedules_path
  end


  def create_multiple
    start_date = *params[:start_date].values_at(:year, :month, :day).map{|c| c.to_i}
    end_date = *params[:end_date].values_at(:year, :month, :day).map{|c| c.to_i}
    values = params[:levels].values.each { |v| v.merge!(start_date: start_date, end_date: end_date)}
    if @levels = Level.create(values)
      flash[:notice] = "Successfully created schedules"
    end
    respond_with @schedules, location: schedules_path
  end
end

app/helpers/schedules_helper.rb
module SchedulesHelper

  def total_schedule_points(schedule)
    sum = 0
    schedule.tasks.each { |t| sum += t.points}
    sum
  end

  def can_edit_schedule?(schedule)
    can_edit_start_date?(schedule) || can_extend_end_date?(schedule)
  end

  def can_edit_start_date?(schedule)
    schedule.start_date > Date.today
  end

  def can_extend_end_date?(schedule)
    schedule.end_date >= Date.today
  end

  def can_assign_default?(levels)
    levels.each do |l|
      return false if l.default
    end
    true
  end

  def can_delete?(schedule)
    schedule.check_if_can_destroy
  end
end

app/views/schedules/_activity_task_fields.html.haml
.control-group
  .control-label
    = f.label :activity, class: "label"
  .controls
    = f.select :activity_id, options_for_select(Activity.all.map{|a| [a.title, a.id]}), class: "span2"
%br
- if f.object.new_record?
  - f.object.tasks.build
= f.fields_for :tasks do |t|
  .row
    = t.error_messages header_tag: 'h4', message: nil, class: 'alert alert-error'
  = render partial: "task_fields", locals: {f: t}
.add-task
  = link_to_add_fields t("schedule.add_task"), f, :tasks

app/views/schedules/_edit_schedule_date.html.haml
= form_tag update_multiple_schedules_path, method: :put do
  .modal-body
    = hidden_field_tag :prev_start_date, @start_date
    = hidden_field_tag :prev_end_date, @end_date
    .fieldset
      = label_tag :start_date
      - if can_edit_start_date?(@schedules.first)
        = select_date @start_date, {order: [:day, :month, :year], prefix: "start_date"}, {class: "span2"}
      - else
        .label.info
          = @start_date
    .fieldset
      = label_tag :end_date
      = select_date @end_date, {order: [:day, :month, :year], prefix: "end_date"}, class: "span2"

  .modal-footer
    = submit_tag "Update all", class: "btn btn-success"

app/views/schedules/_level-details.html.haml
.levels-builder
  .control-group
    .control-label
      = f.label :level_name
    .controls
      = f.text_field :name
  - schedule = level.schedules.build
  .control-group
    = f.fields_for :schedules, schedule do |s|
      = render partial: "schedule-details", locals: {f: s}
    .add-task
      = link_to_add_schedule t('schedule.add_alternative'), f, :schedules

app/views/schedules/_schedule-details.html.haml
.tasks-builder
  .control-group
    .control-label
      = t('schedule.title')
    .controls
      = f.text_field :title, placeholder: t('common.title')
      = f.hidden_field :zone, value: current_user.gender

app/views/schedules/_schedule-form.html.haml
.control-group.schedule-fields
  .control-label
    = t('common.start_date')
  .controls
    = select_date Date.today + 1, {order: [:day, :month, :year], prefix: "start_date"}, {class: "span2"}
.control-group.schedule-fields
  .control-label
    = t('common.end_date')
  .controls
    = select_date Date.today + 8, {order: [:day, :month, :year], prefix: "end_date"}, {class: "span2"}
- level = Level.new
= fields_for "levels[#{level.id}]", level do |l|
  = render partial: "level-details", locals: {f: l, level: level}
  .add-task
    = link_to_add_level t('level.add'), l, level
  

app/views/schedules/_schedule.form.html.haml
.container
  = link_to "<< All Schedules", schedules_path, class: "btn"
  %h3 
    = @schedule.title
    %span.label
      = @schedule.level.name
  = form_for @schedule, method: :put do |f|
    .row
      = f.error_messages header_tag: 'h4', message: nil, class: 'alert alert-error'
    .tasks-builder
      = f.text_field :title, placeholder: t('common.title'), class: "span3"
      = f.fields_for :activity_tasks do |t|
        .row
          = t.error_messages header_tag: 'h4', message: nil, class: 'alert alert-error'
        - t.object.tasks.build
        = render partial: "activity_task_fields", locals: {f: t}
      .add-task
        = link_to_add_fields t("schedule.add_category"), f, :activity_tasks
      
    .action
      = f.submit "Save", class: "btn btn-success"

app/views/schedules/_task_fields.html.haml
.control-group
  .controls.controls-row
    = f.text_field :description, class: "span3", placeholder: t('common.task')
    = f.number_field :points, class: "span1", placeholder: t('common.points')
    %label.checkbox.span
      = f.check_box :_destroy
      %span
        = t('common.remove')
    - if sis_zone?
      .span2
        = t('task.duplicate')
      = f.check_box :common, class: "span2"

app/views/schedules/edit.html.haml
= render partial: "schedule.form"

app/views/schedules/edit_multiple.html.haml
#new-schedule
  %h3 
    = t('schedule.fill')
    = form_tag update_multiple_schedules_path, method: :put do
      .row-fluid
        .fieldset.inline
          = label_tag :start_date
          = select_date @schedules.first.start_date, order: [:day, :month, :year], class: "span2", prefix: "start_date"
          = label_tag :end_date
          = select_date @schedules.first.end_date, order: [:day, :month, :year], class: "span2", prefix: "end_date"
      .row-fluid
        - @schedules.each do |schedule|
          .span6.tasks-builder
            = fields_for "schedules[#{schedule.id}]", schedule do |s|
              = s.text_field :title, placeholder: t('common.title'), class: "span6"
              - schedule.tasks.build
              = s.fields_for :tasks do |t|
                = render partial: "task_fields", locals: {f: t}
              .add-task
                = link_to_add_fields "Add Task", s, :tasks 
                

      .row-fluid
        = submit_tag "Save", class: "btn btn-success"

app/views/schedules/edit_multiple.js.haml
:plain
  var drawer_data = $("#{escape_javascript(render(partial: 'schedules/edit_schedule_date', locals: {start_date: @start_date, end_date: @end_date}))}");
  $("#date-form").html(drawer_data);

app/views/schedules/index.html.haml
.container.db-wrapper
  %h3
    Schedules
    %span.pull-right
      = link_to "New schedule", "#", class: "btn", data: {toggle: "modal", target: "#new-schedule"}
  .row
    - if @schedules.present?
      - grouped_schedules = @schedules.group_by(&:start_date)
      - grouped_schedules.keys.each do |s|
        %table.table
          %thead
            %tr
              %th Start date
              %th End Date
              %th
          %tbody
            %tr.success
              %td= s.strftime('%d-%m-%Y')
              %td= grouped_schedules[s].first.end_date.strftime('%d-%m-%Y')
              %td
                - if can_edit_schedule?(grouped_schedules[s].first)
                  = link_to "Edit Date", edit_multiple_schedule_path(grouped_schedules[s].first), data: {toggle: "modal", remote: true, target: "#edit-schedule-date"}, class: 'btn'
        - levels = grouped_schedules[s].group_by(&:level)
        - levels.keys.each do |level|
          %table.table.table-striped
            %thead
              %tr
                %th Title
                %th Created at
                %th Total Tasks
                %th Total points
                %th
            %tbody
              %tr.info
                %td{colspan: 3}
                  = level.name
                  - if level.default
                    %span.label= t('level.default_level')
                %td
                  = link_to t('level.add_follow_up_messages'), level_follow_up_messages_path(level)
                %td
                  = form_for level, method: :put, class: "form-inline" do |f|
                    .span2
                      = f.check_box :default, class: "checkbox span2 assign-default-level"
                    = f.label t('level.assign_default'), class: "checkbox"
                      
              - levels[level].each do |schedule|
                %tr
                  %td
                    = link_to schedule_path(schedule) do
                      = schedule.title
                  %td
                    = schedule.created_at.to_date
                  %td
                    = schedule.tasks_count
                  %td
                    = schedule.total_points
                  %th 
                    = link_to t("common.show"), schedule_path(schedule)
                    - if can_delete?(schedule)
                      |
                      = link_to t("common.delete"), schedule_path(schedule), method: :delete
    - else
      .alert
        No schedules yet!
#new-schedule.modal.hide.fade{tabindex: "-1", role: "dialog"}
  .modal-header
    = link_to "×", '', class: "close", :'data-dismiss' => "modal", :'aria-hidden' => true
    %h3 
      = t('schedule.new')
  = form_tag create_multiple_schedules_path, method: :put, class: 'form-horizontal' do
    .modal-body
      = render partial: "schedule-form"
    .modal-footer
      = submit_tag "Create", class: "btn btn-success"

#edit-schedule-date.modal.hide.fade{tabindex: "-1", role: "dialog"}
  .modal-header
    = link_to "×", '', class: "close", :'data-dismiss' => "modal", :'aria-hidden' => true
    %h3 
      = t('schedule.edit_date')
  #date-form

app/views/schedules/new.html.haml
#new-schedule
  %h3 
    = t('schedule.new')
    = form_tag create_multiple_schedules_path, method: :put do
      .row-fluid
        .fieldset.inline
          = label_tag :start_date
          = select_date Date.today + 1, order: [:day, :month, :year], class: "span2", prefix: "start_date"
      .row-fluid
        - @schedules.each do |schedule|
          .span6.tasks-builder
            = fields_for "schedules[#{schedule.id}]", schedule do |s|
              = s.text_field :title, placeholder: t('common.title'), class: "span6"
              - schedule.activity_tasks.build
              = s.fields_for :activity_tasks do |t|
                = render partial: "activity_task_fields", locals: {f: t}
            .add-task
              = link_to_add_fields t("schedule.add_category"), schedule, :activity_tasks 
                

      .row-fluid
        = submit_tag "Create", class: "btn btn-success"

app/views/schedules/show.html.haml
= link_to "<< All Schedules", schedules_path, class: "btn"
%h3 
  = @schedule.title
  %span.label
    = @schedule.level.name
= form_for @schedule, method: :put do |f|
  .row-fluid
    .span6.tasks-builder
      = f.text_field :title, placeholder: t('common.title'), class: "span6"
      = f.fields_for :tasks do |t|
        = render partial: "task_fields", locals: {f: t}
      .add-task
        = link_to_add_fields "Add Task", f, :tasks 
    
  .row-fluid
    = f.submit "Save", class: "btn btn-success"